name: Build
on:
  push:
    branches:
      - master
jobs:
        - name: Appknox GitHub action
          uses: appknox/appknox-github-action@1.0.0
      with:
        appknox_access_token: ${{ secrets.APPKNOX_ACCESS_TOKEN }}
        file_path: app/mfva_v1.1.1.apk
        risk_threshold: MEDIUM
